name: mutfold
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - conda-forge::python=3.10
  - conda-forge::setuptools=59.5.0
  - conda-forge::pip
  # use the following dependencies if you are going to use ESMFold
  - bioconda::hmmer==3.3.2
  - bioconda::hhsuite==3.3.0
  - bioconda::kalign2==2.04
  - conda-forge::cudatoolkit==11.3.*
  - conda-forge::einops
  - conda-forge::hydra-core
  - conda-forge::fairscale
  - conda-forge::omegaconf
  - conda-forge::pytest
  - conda-forge::pdbfixer
  - conda-forge::openmm=7.5.1
  - pytorch::pytorch=1.12.*
  - conda-forge::pandas
  - pip:
      - requests==2.26.0
      - typing-extensions==3.10.0.2
      # use the following dependencies if you are going to use ESMFold
      - pytorch_lightning==1.5.10
      - deepspeed==0.5.9 # need to debug deepseed (import torch._six deprecated)
      - git+https://github.com/NVIDIA/dllogger.git
      - numpy==1.21.2
      - biopython==1.79
      - scipy==1.7.1
      - PyYAML==5.4.1
      - dm-tree==0.1.6
      - tqdm==4.62.2
      - ml-collections==0.1.0
      - wandb==0.12.21
      - stmol==0.0.9
      - streamlit==1.28.0
      - mysql-connector-python==8.0.32      
